### ISSUE TITLE
uninitialized constant Devise::COSIGNClient

### ISSUE THREAD

**Issue by wazynski** [mjgiarlo/devise_cosign_authenticatable#1]
We are looking to work with devise and cosign but we are getting a uninitialized constant Devise::COSIGNClient error. 

We have followed the installation guide and can't see where we are going wrong. Does this still work and is it supported?

**Comment by mjgiarlo** [comment]
Unfortunately this never worked. I started down the path of building this gem but didn't get very far. Sorry!
